# Assignment 13: Data Gathering, Preprocessing & EDA

## PART 1 — Data Gathering (Multiple Sources)

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

### Task 1: Load Data from CSV
1. Download any dataset from Kaggle (CSV format).
2. Load it using Pandas.
3. Print:
o Shape of the dataset
o Column names
o First 5 rows
o Other Preprocessing Techniques discussed in the lectures

In [ ]:
# Dataset is about - Global Academic Retractions (2000–2025)
df = pd.read_csv('global_academic_retractions_2000_2025.csv')
print(df.shape)
print(df.columns)
df.head().T

### Task 2: Load Data from JSON
1. Create or download a small JSON file (example: product data, user data).
2. Load it using Pandas.
3. Convert it into a DataFrame.
4. Print the DataFrame.

In [ ]:
import json
# write to json
product = {'Type1': [['name', 'price', 'category'], ['Apple', 100, 'Fruit'], ['Mango', 200, 'Fruit'],  ['Bread', 50, 'Bakery'], ['Butter', 80, 'Dairy'], ['Milk', 120, 'Dairy']],
           'Type2':{'name':['Banana', 'Kiwi', 'Dates', 'Cream', 'Shampoo'], 'price':[100, 300, 200, 500, 1000], 'category':['Fruit', 'Fruit', 'Fruit', 'Beauty', 'Beauty']}}
with open('product.json', 'w+') as f:
    json.dump(product, f, indent=4)

# read data from json
with open('product.json', 'r+') as f:
    data = json.load(f)

if data is not None:
    df_json = pd.DataFrame(data['Type1'])
    df1 = pd.DataFrame(data.get('Type2'))
# print(df_json.iloc[0])
df_json.columns = df_json.iloc[0]
df_json = df_json.iloc[1:].reset_index(drop=True)
print(df_json)
print(df1)

### Task 3: Load Data from SQL Database
1. Create a SQLite database (sample.db)
2. Create a table named employees with columns:
o id
o name
o department
o salary
3. Insert at least 5 records.
4. Read the table into Pandas using SQL query.
5. Display the DataFrame.

In [ ]:
import sqlite3

try:
    # Connect to SQLite Database and create a cursor
    conn = sqlite3.connect('sample.db')
    cursor = conn.cursor()
    print('DB Init')

    # Execute a query to create table
    query = "Create Table IF NOT EXISTS Employee (id integer PRIMARY KEY, name varchar(50), department varchar(50), salary integer);" \
    "Insert into Employee values (1, 'Emp1', 'A', 100000); Insert into Employee values(2, 'Emp2','A', 15000); Insert into Employee values(3, 'Emp3','B', 12000); Insert into Employee values(4, 'Emp4', 'c', 15600); Insert into Employee values(5, 'Emp5', 'B', 60000);"
    cursor.executescript(query)

    # Close the cursor after use
    cursor.close()

except sqlite3.Error as error:
    print('Error occurred -', error)

finally:
    # Ensure the database connection is closed
    if conn:
        conn.close()
        print('SQLite Connection closed')

In [ ]:
try:
    # Connect to SQLite Database
    conn = sqlite3.connect('sample.db')
    df2 = pd.read_sql('select * from Employee',conn )
except sqlite3.Error as error:
    print('Error occurred -', error)
finally:
    # Ensure the database connection is closed
    if conn:
        conn.close()
print(df2)

### Task 4: API Mini Project (TMDB API)
Mini Project: Movie Data Collector
1. Create a free account on TMDB (The Movie Database)
2. Generate an API key.
3. Using Python (requests library):
o Fetch popular movies data
o Extract fields:
Movie title
Release date
Rating
Popularity
Any Columns of Your Choice
4. Convert the API response into a Pandas DataFrame.
5. Save the collected data into a CSV file named tmdb_movies.csv.
Extra (optional): Fetch data for top-rated movies as well.

In [ ]:
access_token = 'eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxZTNkMGJlM2UwMTI1NTU5MGU3NDdiOWY0ZTE1YTc2MSIsIm5iZiI6MTc5MDA4MzY1Mi42NjIwMDAyLCJzdWIiOiI2YWIyODI0NGEzMmUyOWQ0MzZkMmMyZjYiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.NclH_PpRVhf9M1lP-7M9CFqhFolnJ_xYu0q9SUreb6E'
api_key = '1e3d0be3e01255590e747b9f4e15a761'

# fetch data from API
import requests
import time

# trending movies
url = "https://api.themoviedb.org/3/trending/movie/day?language=en-US"

# Top rated movies
url_top = "https://api.themoviedb.org/3/movie/top_rated?language=en-US"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "accept": "application/json",
    "Authorization": f"Bearer {access_token}",
    "Accept-Encoding": "*",
    "Connection": "keep-alive"
}

time.sleep(1)
response = requests.get(url, headers=headers)
data = response.json()
with open('moviesdata.json', 'w+') as f:
    json.dump(data, f, indent=4)
df_movie = pd.DataFrame(data['results'])

#top rated movies
time.sleep(1)
response = requests.get(url_top, headers=headers)
data = response.json()
with open('topmoviesdata.json', 'w+') as f:
    json.dump(data, f, indent=4)
df_movie_top = pd.DataFrame(data['results'])

In [21]:
df_movie

,adult,backdrop_path,id,title,original_title,overview,poster_path,media_type,original_language,genre_ids,popularity,release_date,softcore,video,vote_average,vote_count
0,False,/8giIQcHpxgsPVP6c7aQtHl3txuh.jpg,1607127,One Last Shot,One Last Shot,Navy Seal Jake Harris must stop a team of merc...,/niQ4NBh2jqAf1hDZP5m6ReWFAb7.jpg,movie,en,"[28, 53]",2.8194,2026-09-22,False,False,8.500,6
1,False,/1CIaRYKf3zg2Xyce1CSfCMg2Vfw.jpg,1423191,Resident Evil,Resident Evil,Medical courier Bryan unwittingly finds himsel...,/i7UyjfPio0VFHB9rBUZSFyhOoM8.jpg,movie,en,"[27, 878, 12]",607.7799,2026-09-16,False,False,7.359,294
2,False,/lneqlgbg3XUjNaeGYk8arhgzczo.jpg,445466,Idiots,Idiots,When two unqualified bozos are hired to transf...,/l1JFNC1SdgyXVr7BaD5ehaYBvOC.jpg,movie,en,"[35, 80]",9.1919,2026-08-20,False,False,6.900,9
3,False,/hyN1E14gNxx8biNBOv1daJrmGkK.jpg,1477712,Ice Cream Man,Ice Cream Man,An idyllic summer town descends into madness w...,/lNBxToxHWrzmkqeFnf1XADUTxQq.jpg,movie,en,"[27, 35, 53]",21.8014,2026-08-03,False,False,4.675,63
4,False,/mqO2Q8BeCuESJUVZgwyWRDa9Ux9.jpg,675871,Super Troopers 3,Super Troopers 3,When Farva's over-the-top Indian engagement to...,/iZK7dZXAZEqAt5TYionYretrgWg.jpg,movie,en,"[35, 80, 9648]",13.8393,2026-08-06,False,False,6.500,19
5,False,/bicMU6xVD5deVyKP2azpyx7xkmH.jpg,1263337,Heart of the Beast,Heart of the Beast,"After a harrowing plane crash, Special Forces ...",/1ApfSA8JTqeha3GTFEY8syV4auq.jpg,movie,en,"[12, 53]",49.2589,2026-09-19,False,False,7.900,18
6,False,/b9q9VmbXDvJmTziRqkwdEmFdwhr.jpg,1101383,The End of Oak Street,The End of Oak Street,After a mysterious cosmic event rips Oak Stree...,/fYXqpgPmHMphSF2W30GbTeJVIa5.jpg,movie,en,"[878, 9648, 53]",528.4832,2026-08-12,False,False,7.020,1397
7,False,/b7PtCwsuMw84REQq15nmQgT9UXN.jpg,1248832,Digger,Digger,The most powerful man in the world embarks on ...,/1ATXKrIPJyKNwnJ6lcG088Sa6zi.jpg,movie,en,[35],28.4493,2026-09-30,False,False,0.000,0
8,False,/ftFf9sfJq69xJ0AuiaIuDKBtfzg.jpg,1341138,Spa Weekend,Spa Weekend,Four lifelong friends realize that somewhere b...,/uhx4YjT9YbSxrKVE7GWJdjI412J.jpg,movie,en,[35],32.9245,2026-08-20,False,False,6.703,37
9,False,/2o9FzuBzCqrDTdlHRuEVnGD2d5h.jpg,1465063,Forgotten Island,Forgotten Island,"While celebrating their last night together, h...",/myd1K3gefdNAWFsGNRDdMeiK9Qg.jpg,movie,en,"[16, 12, 14, 35, 10751]",39.7078,2026-09-10,False,False,7.900,10
10,False,/qeQJx07rK2xm8SD2sJxFKhE7gs0.jpg,969681,Spider-Man: Brand New Day,Spider-Man: Brand New Day,Fighting crime full-time as Spider-Man in a wo...,/bjiS5ipwxb9JFy3XRRN4OAilSeX.jpg,movie,en,"[878, 28, 12]",666.5009,2026-07-29,False,False,7.862,2822
11,False,/iuylzRSllrGn7YB322kwKoOVMcq.jpg,1368337,The Odyssey,The Odyssey,"Odysseus, the legendary King of Ithaca, embark...",/5rhTDKUhPYvpdQIijFIs5VoWsON.jpg,movie,en,"[12, 28, 14]",355.3396,2026-07-15,False,False,8.000,3852
12,False,/d1n2ySWSanU34eEsluRjfrjRq52.jpg,1240889,Teenage Sex and Death at Camp Miasma,Teenage Sex and Death at Camp Miasma,"After years of slapdash sequels, the Camp Mias...",/6Q6Zo6GNXMLP600OJSh6MhW21um.jpg,movie,en,"[35, 27, 10749]",101.3883,2026-08-06,False,False,6.500,156
13,False,/5m1j7Wibh3HnZq5QHm97v8dI3GH.jpg,1514863,Best of the Best,Best of the Best,Two childhood besties join UCLA's competitive ...,/dbP661svmn7XZq3TdSmSUI5UKQJ.jpg,movie,en,[35],58.5972,2026-09-18,False,False,4.700,39
14,False,/dqmMWNWfLnExDRpMtIMqI97GQFR.jpg,1083381,Backrooms,Backrooms,A strange doorway appears in the basement of a...,/rhGx6E3qRNMgj3i5su2oukNHwIQ.jpg,movie,en,"[27, 9648, 878]",90.2978,2026-05-27,False,False,7.000,3373
15,False,/4E5RVsSUG1A4Adwbqupu5w6kofZ.jpg,1375441,Primetime,Primetime,"In 2006, To Catch a Predator host Chris Hansen...",/51VDtNQFuD2I86hrT4ekytg9Dq3.jpg,movie,en,"[18, 53]",24.9578,2026-09-23,False,False,6.500,4
16,False,/5H5YphHsQmkQhrw13Wv1whCZKtN.jpg,1153576,Street Fighter,Street Fighter,"In 1993, estranged Street Fighters Ryu and Ken...",/utKzCSCz2HtXwcDGfWLj2IHhSob.jpg,movie,en,"[28, 14]",15.5214,2026-10-14,False,False,0.000,0
17,False,/c6BPbkO5Npt1OdwttAxCFo06wtH.jpg,1108427,Moana,Moana,"Teenage Moana answers the Ocean's call and, fo...",/gaet1xQ2nxrG0V1Ep9T20ZMNEIC.jpg,movie,en,"[10751, 14, 35, 12]",194.5217,2026-07-08,False,False,7.417,741
18,False,/rZfmzpixLKLR3Hg2u0WgC7XLFl8.jpg,1339713,Obsession,Obsession,"After breaking the mysterious ""One Wish Willow...",/bRwnj8WEKBCvmfeUNOukJPwB43K.jpg,movie,en,"[27, 53]",142.2624,2026-05-13,False,False,8.194,5674
19,False,/9qxyrJfjk577ym5WD6HCDmunoyO.jpg,1283515,Verity,Verity,Lowen Ashleigh is hired by Jeremy Crawford to ...,/97y0RdzRIeZ2j6se98hRQpxz3eR.jpg,movie,en,"[9648, 53]",19.0824,2026-09-30,False,False,0.000,0

In [22]:
df_movie_selected_fields = df_movie[['title', 'release_date', 'vote_average', 'popularity', 'overview']]
df_movie_selected_fields.columns = ['Title', 'Release_date', 'Rating', 'Popularity', 'Overview']
df_movie_selected_fields.head()

,Title,Release_date,Rating,Popularity,Overview
0,One Last Shot,2026-09-22,8.500,2.8194,Navy Seal Jake Harris must stop a team of merc...
1,Resident Evil,2026-09-16,7.359,607.7799,Medical courier Bryan unwittingly finds himsel...
2,Idiots,2026-08-20,6.900,9.1919,When two unqualified bozos are hired to transf...
3,Ice Cream Man,2026-08-03,4.675,21.8014,An idyllic summer town descends into madness w...
4,Super Troopers 3,2026-08-06,6.500,13.8393,When Farva's over-the-top Indian engagement to...

In [23]:

df_movie_top_selected_fields = df_movie_top[['title', 'release_date', 'vote_average', 'popularity', 'overview']]
df_movie_top_selected_fields.columns = ['Title', 'Release_date', 'Rating', 'Popularity', 'Overview']
df_movie_top_selected_fields.head()

,Title,Release_date,Rating,Popularity,Overview
0,One Last Shot,2026-09-22,8.500,2.8194,Navy Seal Jake Harris must stop a team of merc...
1,Resident Evil,2026-09-16,7.359,607.7799,Medical courier Bryan unwittingly finds himsel...
2,Idiots,2026-08-20,6.900,9.1919,When two unqualified bozos are hired to transf...
3,Ice Cream Man,2026-08-03,4.675,21.8014,An idyllic summer town descends into madness w...
4,Super Troopers 3,2026-08-06,6.500,13.8393,When Farva's over-the-top Indian engagement to...

## PART 2 — Data Preprocessing & Cleaning (Kaggle Dataset)

### Task 5: Understanding the Data
1. Check dataset shape.
2. Display column data types.
3. Identify numerical and categorical columns.
4. Check missing values count per column.
5. Rest of The Known Techniques